### ISSUE TITLE
Unable to use examples on RPI3 B+

### ISSUE THREAD

**Issue by lostPixels** [alexeden/rpi-led-matrix#7]
Hello, 

This is a very well made library and I am experimenting with using it to drive an LED matrix that I just bought.

My setup is:
An RPI 3 B+
Raspbian Buster
Adafruit LED Matrix Bonnet
Cheapo Aliexpress LED Matrix 64x32 (confirmed working with Adafruit lib)
Node v13.3
Sound module turned off
No soldering (so it's in convenience mode)

I am unable to get any example working, or even write a basic test that lights up the screen. I cloned your repo and tried running the examples with no luck. Some times the RPI just hangs, and other times I get this error:

```
> rpi-led-matrix@1.8.0 example /home/pi/shared/led-testing/rpi-led-matrix
> ts-node -P examples/tsconfig.json "examples/kitchen-sink.ts"

*** Error in `node': corrupted size vs. prev_size: 0x042fd248 ***
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! rpi-led-matrix@1.8.0 example: `ts-node -P examples/tsconfig.json "examples/kitchen-sink.ts"`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the rpi-led-matrix@1.8.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-11T12_52_02_175Z-debug.log
```

My config has been stripped down to simply include these options:

```
export const matrixOptions: MatrixOptions = {
  ...LedMatrix.defaultMatrixOptions(),
  rows: 32,
  cols: 64,
  //chainLength: 2,
  hardwareMapping: GpioMapping.AdafruitHat,
  //parallel: 3,
  // pixelMapperConfig: LedMatrixUtils.encodeMappers(
  //   { type: PixelMapperType.Chainlink }
  // ),
  // pixelMapperConfig: LedMatrixUtils.encodeMappers({ type: PixelMapperType.U }),
};

```

Any assistance would be very much appreciated! There's not really any other maintained Node libs to power these matrices.

**Comment by alexeden** [comment]
Hey James, that's really bizarre. I've never seen a `Error in 'node': corrupted size vs. prev_size` before, and googling it doesn't yield much in the way of useful information. Your setup seems nearly identical to what I used when developing the library, except that I _think_ I was using node 12. I'll investigate it tomorrow with node 13 and see if I can reproduce the problem. In the interim, if you're using nvm, you might try running `$ nvm i 12 && nvm use 12`, and see if using node 12 fixes it.

**Comment by Fensterbank** [comment]
Hi,

it seems I have the same issue.
I am using Rasperry Pi 4 Model B and tried it with Node 10 and Node 13.
I'm also using `hardwareMapping: GpioMapping.AdafruitHat`, since I have the Adafruit LED Matrix with the Adafruit Bonnet. With these configuration values the other examples (native and python are working).

I do not always get `corrupted size vs. prev_size`, most times I get `free(): invalid pointer`.
It only crashes on `hardwareMapping: GpioMapping.AdafruitHat`. With another `hardwareMapping`, it does not crash, but it - of course - also doesn't work.

**console output:**
```
root@raspberrypi:/home/pi/rpi-led-matrix-fire# ./bin/run 
Building the matrix 64x32
Destroying matrix
corrupted size vs. prev_size
Abgebrochen
root@raspberrypi:/home/pi/rpi-led-matrix-fire# ./bin/run 
Building the matrix 64x32
Destroying matrix
free(): invalid pointer
Abgebrochen
```

**This is my simple code:**
```typescript
  static flags = {
    // add --version flag to show CLI version
    version: flags.version({char: 'v'}),
    help: flags.help({char: 'h'}),
    'led-rows': flags.integer({default: 32}),
    'led-cols': flags.integer({default: 64}),
    'led-slowdown-gpio': flags.integer({default: 4}),
  }

  async run() {
    const {flags} = this.parse(RpiLedMatrixFire)

    this.log(`Building the matrix ${flags['led-cols']}x${flags['led-rows']}`)

    const matrix = new LedMatrix(
      {
        ...LedMatrix.defaultMatrixOptions(),
        rows: flags['led-rows'] as 32 | 16 | 64,
        cols: flags['led-cols'] as 32 | 16 | 64,
        hardwareMapping: GpioMapping.AdafruitHat,
        chainLength: 1,
      },
      {
        ...LedMatrix.defaultRuntimeOptions(),
        gpioSlowdown: flags['led-slowdown-gpio'] as 0 | 1 | 2 | 3 | 4,
      },
    )
    matrix
    .clear()            // clear the display
    .brightness(100)    // set the panel brightness to 100%
    .fgColor(0x0000FF)  // set the active color to blue
    .fill()             // color the entire diplay blue
    .sync()
  }
```

I don't know, how to get this library running at the moment... :(
@lostpixels: Did you find any solution or workaround on your issue in the meantime?

**Comment by lostPixels** [comment]
Hi @Fensterbank, I'm afraid I was unable to find a solution to this issue. I tried a lot of the different examples and couldn't get it to do anything.

**Comment by alexeden** [comment]
@lostPixels @Fensterbank  Hey guys, sorry for the lack of feedback; been abroad for several weeks. Promise to look into this this weekend and get back to ya!

**Comment by Fensterbank** [comment]
Thanks, I really appreciate it.
I took a deeper look at it. Since the error occured on a random point and I could not catch it or print a stack trace, I figured out it happens when the node script is finished.

The whole thing works asynchronous I assume, so I think I running to the point that the node script is finished and the process get closed, which kills the native bindings in the middle, so we end up in broken pointers etc.
If I put an endless loop at the end of the script (I mean, this is anyway how it will work), I don't get any error messages.

But I still don't have anything drawn on the screen, it stays black.

**Comment by mgreenw** [comment]
I believe this is an issue of the submodule not being up to date with master. The master branch adds support for Pi 4+.

**Comment by MargaretKrutikova** [comment]
@alexeden could you please publish the latest version with the up-to-date submodule on `npm`?
I saw that `1.8.0` is the latest release, but `npm` still has `1.7.2`.

For me it draws, but crashes sporadically, with different exceptions, like `corrupted size vs. prev_size`, or `free(): invalid pointer`. I am using raspberry pi 2 with `node` 12. Would be really great to understand why this happens and help fix the problem 😄

**Comment by alexeden** [comment]
Hey everyone, I finally had time to wire up a Pi 4 and update this library (new version is 1.9.0 @MargaretKrutikova  @mgreenw).

The submodule has been updated to the latest and I've [added new enum values for multiplexing and addressing types.](https://github.com/alexeden/rpi-led-matrix/commit/ee9180153e8a5849b47586e19aa46bdf50ddbd00)

I tested it using 3 chains with 2, 64x32 panels each. Node 12.5.0. I use the active 3 adapter so my GPIO mapping is set to `Regular`. I'd appreciate it @Fensterbank if you could try it again using the Adafruit hat and the updated library version. If you still have an issue, I'll dig up my own hat and see if I can reproduce it.

I did twice see the issue with the example scripts just doing nothing, as mentioned by @lostPixels. I'm not _quite_ sure what the exact cause is. I got it to work again by clearing `/build` and `node_modules` and reinstalling/rebuilding the binaries *while not in `sudo`.* Again, not sure if there really is some issue with permissions, and I don't want to cargo cult this, but that did seem to fix it.

Please let me know if ya'll are still having issues. Feel free to open another issue if so!

**Comment by lostPixels** [comment]
Thank you very much for the followup @alexeden!  I'll give this a whirl and let you know how it goes.

**Comment by Fensterbank** [comment]
Thank you for your work! I will try to give you a feedback with my setup at Friday.

**Comment by Fensterbank** [comment]
I tested it now with the Raspberry Pi 4 Model B and can confirm **it is working**.

In my tests yesterday I had always the issue, that my node app terminated after exactly 24 seconds with either `free(): invalid pointer` or `corrupted size vs. prev_size`.
Now (after a reboot and a night of sleep) it runs without crash, so I assume there may be some random problems somewhere but for now it is working without any further crashes.

I did not figure out how to run the examples in this repository, I followed the instructions but it always fails with
```
node_modules/bindings/bindings.js:126
Error: Could not locate the bindings file.
```
... but I did not invest more time in it since my own node app using the release 1.9.0 is working fine.

Thanks for your update. 👏
I'm looking forward to start working with your library.
